### ISSUE TITLE
Automated script to get versionista data into a database

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/versionista-outputter#4]
I came to the Data Rescue SFBay event on Saturday (2017-02-11) and wound up talking with @titaniumbones about getting the data that’s currently being pulled by `versionista-outputter` and placed in CSVs and a Google spreadsheet into a a simple database, on top of which we can later host a better UI, filtering workflow, etc. I was asked to articulate what I thought would be a good approach in Github issues. (So I hope here is an appropriate place; let me know if not!)

It seems like there are a huge number of ideas going on (https://github.com/edgi-govdata-archiving/overview/issues/28, https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/17, https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/16, https://github.com/edgi-govdata-archiving/version-tracking-ui/issues/10), so I’m thinking starting with something really small and simple that can be expanded upon makes sense here.

The basic idea is to have a server that:

1. Acts as an API to a database of pages and their diffs. It should be able to take the data storage role of the Google spreadsheet by storing a list of pages, each with a URL to current diff, some simple metadata, and then the analysts’ evaluation of the diff.
2. It should be able to update itself automatically by running a script that is pretty similar to `versionista-outputter` on a simple schedule.

There’s plenty of room to grow from there—storing actual pages instead of links to Versionista diffs, pulling content from Pagefreezer instead of/alongside Versionista, piping pages through any filtering tools that are developed, etc. But simply doing what the spreadsheet is doing will be an good start and is very doable.

For the database, I think the simple place to start is a couple tables in Postgres DB:

1. List of pages, with columns for:

  ```
  url
  page title (current title? title at time added?)
  site
  date added/first found
  date of last change
  (date of last check?)
  ```

2. List of page versions, each associated with a page from table (1)

  ```
  id
  date
  previous version (pointer to another row in this table)
  diff with previous (Versionista URL; this might go away if we move to doing our own diffing)
  diff with first (Versionista URL; this might go away if we move to doing our own diffing)
  metadata (stored as jsonb)
  ```

  The last column would store things like analyst notes or the change categories analysts are tracking. Since it’s JSON data, it’s semi free-form and can support different content over time—I’m sure the way we want to evaluate a page can & has changed over time. This could also hold meta for or created by future filtering systems.

The script to gather input could start off by simply running as a cron job. https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/16 makes it sound like this script is currently run about once every three days, but if a different schedule is better, let me know.

I plan to make a new repo for this (happy to move it into `edgi-govdata-archiving` org) and implement it in Rails (since `versionista-outputter` is already in Ruby; if anyone thinks Rails is too heavy, I’ve done Sinatra + ActiveRecord a couple times and that can run much lighter) for Heroku (so we don’t need to worry about sys-admin and database tasks; I’m checking around to see if I can get us some free credit, too).

Apologies if this is overlapping with any existing effort or work—I’m still trying to get a clear lay of the land. Let me know if this not a helpful idea or even if I’ve just written this all down in the wrong place!

Otherwise, if people think this approach seems sensible, I’ll get to work on it straight away. 👟

**Comment by KrishnaKulkarni** [comment]
@Mr0grog Sounds good. Keep me updated :)

**Comment by titaniumbones** [comment]
@KrishnaKulkarni how's that filter ocming? It's my birthday in just 363 days!

**Comment by KrishnaKulkarni** [comment]
It's coming! Faster than you'd expect! Happy belated birthday!

**Comment by KrishnaKulkarni** [comment]
@titaniumbones ^

**Comment by Mr0grog** [comment]
OOF, I wound up not having the time I thought I would to work on this last week and than ran into a bunch of odd issues. Anyway, the *very basics* of this are at: https://github.com/edgi-govdata-archiving/webpage-versions-db

Happy to move, rename the repo, etc etc etc.

@KrishnaKulkarni I’ve ported most of what’s in this repo to the `VersionistaService` module in `lib/versionista_service` in that repo. You can initialize a `VersionistaService::Scraper` and go off to the races. There are a few changes, though:

- The initializer takes actual `DateTime` objects, though there is a `from_hours` convenience static method to create a new scraper.
- It can take an `until_time`, which specifies not to take revisions *after* a given time
- There is a `get_all_versions` argument (`true` by default) which determines whether we scrape *every* version in the given timeframe or just the latest (as the script here does)
- It retries URLs that fail to load after: 30 seconds -> 60 seconds -> 120 seconds -> give up (and skips pages that are given up on; the script here throws and stops entirely)
- Can be given a number of seconds to chill out and wait between scraping sites and scraping individual pages of those sites

Don’t know if those changes would be worth back-porting here. They’re a little messy and kludgy :(

No updating of data in the DB yet. UI and reporting also hasn’t had any more than 5 minutes put into it.

I’ve included the hash information in the data and a column in the DB for marking a change as `relevant`; we can use the two together to pre-determine relevance once we make a UI for manually marking a change as not relevant.

Will try and get this running on AWS or Heroku later today.

* * *

Some scraping notes:

- I noticed we have Versionista double-scraping a bunch of pages (as part of different “sites”). e.g. `http://research.noaa.gov/LabsPrograms/OARLabs.aspx` is hit once each as part of the `NOAA - oar.noaa.gov - EoT Primer Seed` and `NOAA - research.noaa.gov` sites. Because they generate different diffs (more below), I’ve kept them separate in the DB here for the sake of code sanity. It’ll be less sanity for analysts, though, so we should figure out how best to clean that up.

- As I worked on this script and looked at the results and data in Versionista, it occurred to me that the hashing method for finding duplicate changes is really diminished by pages that are highly dynamic and generate their content through ASP.net webforms (even if they have the exact same content from a viewer’s perspective, they’ll include some hidden server state information that is different) or JS frameworks like React that will use a lot of generated IDs that are unique on every page load.

  Similarly, changes in the document structure or to text that is entirely hidden also cause kind-of-meaningless diffs. I’m wondering if we should only look at differences in the *text* rather than the source of the pages. We probably also have a lot more freedom to think about better ways to consider content as valid for a diff:

    - If we pull the revision’s content out of Versionista and diff it (instead of using Versionista’s diff at all)
    - Post-Versionista, when we’ll have to consider this all anyway.

**Comment by Mr0grog** [comment]
Oh wow, had totally forgotten this was around. This is long since done :P

The third version (and currently running version) of this work is https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper
