### ISSUE TITLE
Writing CSV Not working

### ISSUE THREAD

**Issue by trinberg** [edgi-govdata-archiving/versionista-outputter#6]
The scraper works and each domain is visited. When the script gets to writing the csv part, it outputs:

Writing the csv...
capybara_script.rb:250:in `+': no implicit conversion of Fixnum into String (TypeError)

from capybara_script.rb:250:in `block (2 levels) in \<main>'

from capybara_script.rb:249:in `each'

from capybara_script.rb:249:in `block in \<main>'

from capybara_script.rb:245:in `each' 

from capybara_script.rb:245:in `\<main>'

**Comment by titaniumbones** [comment]
I think change line 231 to: 
`row_index = ENV["INDEX"].to_i || 0`
http://stackoverflow.com/questions/20356609/ruby-no-implicit-conversion-of-fixnum-into-string-typeerror
give that a try? i don't do ruby though.

**Comment by titaniumbones** [comment]
(found the bug report -- @trinberg if that fixed the issue, can we close this?)
